# Generated by Django 4.1.4 on 2023-01-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lcapi_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dbreport",
            name="account",
        ),
        migrations.AddField(
            model_name="dbreport",
            name="card_id",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
