# Generated by Django 4.1.4 on 2023-01-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcapi_app', '0002_organization_lcapi_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
