# Generated by Django 4.1.4 on 2023-01-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lcapi_app", "0002_remove_dbreport_account_dbreport_card_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dbreport",
            name="discount",
            field=models.FloatField(verbose_name="Discount %"),
        ),
    ]
