# Generated by Django 4.1.4 on 2023-01-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lcapi_app", "0003_alter_dbreport_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dbreport",
            name="discount",
            field=models.FloatField(),
        ),
    ]
