# Generated by Django 4.1.4 on 2023-01-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcapi_app', '0003_organization_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lcapi',
            name='uid',
        ),
        migrations.AlterField(
            model_name='lcapi',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
    ]
