# Generated by Django 4.1.4 on 2023-01-15 18:13

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('lcapi_app', '0005_lcapi_phone_number_alter_lcapi_card_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lcapi',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=9, null=True, region=None, unique=True),
        ),
    ]
