# Generated by Django 4.1.4 on 2023-01-15 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcapi_app', '0006_alter_lcapi_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lcapi',
            name='phone_number',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(regex='\\b5[0-9]{8}\\b')]),
        ),
    ]
